# Site setting
favicon: /favicon.png
avatar_url: https://scontent-tpe1-1.xx.fbcdn.net/hphotos-xat1/t31.0-8/10845647_1113218138694851_6572161589131527754_o.jpg

# User Profile
disqus_shortname: trista515
google_analytics:
twitter:
google_plus:
fb_admins:
fb_app_id:
